name: Grammar Check

on:
  pull_request
  
jobs:
  grammar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install grammar tool
        run: pip install language-tool-python

      - name: Run grammar check
        run: python scripts/grammar_check.py